name: Run tests on pull requests

on:
  pull_request:
    branches: [main, dev]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test
